# This docker-compose file creates a network with two services:
# db: MySQL database service
# phpmyadmin: PHPMyAdmin service for managing the database

services:
  db:
    # Use official MySQL image
    image: mysql
    # Restart the service unless explicitly stopped
    restart: unless-stopped
    # Set the root password for MySQL
    environment:
      MYSQL_ROOT_PASSWORD: password
    # Use a volume to persist the database data
    volumes:
      - db:/var/lib/mysql
    # Expose the port 3306 for MySQL
    ports:
      - 3306:3306
    # Add the service to the 'microservices-net' network
    networks:
      - microservices-net


    
  phpmyadmin:
    # Use official PHPMyAdmin image
    image: phpmyadmin
    restart: unless-stopped
    # Expose the port 5050 for PHPMyAdmin
    ports:
      - 5050:80
    # Set the environment variables for PHPMyAdmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
    networks:
      - microservices-net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - microservices-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    networks:
      - microservices-net


      
  mail-dev:
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025



networks:
  microservices-net:
    # Use bridge network driver
    driver: bridge
volumes:
  db:
