eureka:
    instance:
        hostname: localhost
    client:
        service-url: 
            defaultZone: http://localhost:8761/eureka
epring:
    cloud:
        config:
            override-system-properties: false