spring:
    cloud:
        gateway:
            routes:
                - id: user_app
                  uri: http://user:8090
                  predicates:
                    - Path=/api/user/**

                - id: flight_app
                  uri: http://flight:8092
                  predicates:
                    - Path=/api/flight/**

                - id: reservation_app
                  uri: http://reservation:8091
                  predicates:
                    - Path=/api/reservation/**
            discovery:
                locator:
                    enabled: true


server:
    port: 8222