spring:
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: notification
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: reservationConfirmation:com.erenyavuz.microservices.notification_app.dto.ReservationConfirmation

    mail:
        host: maildev
        port: 1025
        properties:
            mail:
                smtp:
                    trust: "*"
                auth: true
                starttls:
                    enabled: true
                connectiontimeout: 5000
                timeout: 3000
                writetimeout: 5000

email:
    host: maildev
    port: 1025

server:
    port: 8093


