spring:
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
    datasource:
        url: jdbc:mysql://localhost:3306/reservation_app

        username: root
        password: password
        driverClassName: com.mysql.cj.jdbc.Driver

    kafka:
            bootstrap-servers: localhost:9092
            producer:
                key-serializer: org.apache.kafka.common.serialization.StringSerializer
                value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
                properties:
                    spring.json.type.mapping: orderConfirmation:com.erenyavuz.microservices.flight_app.dto.FlightConfirmation




server:
    port: 8091