spring:
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
    datasource:
        url: jdbc:mysql://db:3306/user_app

        username: root
        password: password
        driverClassName: com.mysql.cj.jdbc.Driver




server:
    port: 8090